### PR TITLE
Integrate new input system

### PR DESCRIPTION
**Pull request by Redunderfire**
This branch contains code completely rewriting the character and camera movement logic to use Unity's new messaging-style input system. 
This should allow for different control schemes to be implemented in the future, in addition to general optimization that comes with using a messaging-style input system instead of a constant-polling system.

### CODE REVIEW

**Review by Jakkits — COMMENTED** [review]
Everything looks good and works well so far.

**Comment by Redunderfire** [comment]
Perfect! I'll merge it right away

**Comment by Redunderfire** [comment]
[Remake player movement script using Unity's Input System](https://trello.com/c/87uOGioA/13-remake-player-movement-script-using-unitys-input-system)

**Comment by Redunderfire** [comment]
[Fix supergravity issue](https://trello.com/c/YBdkZnIQ/14-fix-supergravity-issue)

**Pull request merged**
